backend:
  name: github
  repo: marcus-d-cloud/chess-hugo-decap
  branch: main
  auth_scope: repo
  base_url: https://marcus-d-cloud.github.io
  site_domain: marcus-d-cloud.github.io
  client_id: Iv23liOJNzWGfgvRRY8t

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"

    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Inhalt", name: "body", widget: "markdown"}

  - name: "events"
    label: "Veranstaltungen"
    folder: "content/calendar"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Enddatum", name: "end", widget: "datetime", required: false}
      - {label: "Inhalt", name: "body", widget: "markdown"}